package com.matrusneh.app.util

import android.content.Context
import android.os.Environment
import com.itextpdf.text.*
import com.itextpdf.text.pdf.PdfPCell
import com.itextpdf.text.pdf.PdfPTable
import com.itextpdf.text.pdf.PdfWriter
import com.matrusneh.app.data.db.entities.VitalsRecord
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.*

object PdfExportHelper {
    fun generateHealthCard(
        context: Context,
        motherName: String,
        pregnancyWeek: Int,
        vitalsData: List<VitalsRecord>
    ): File {
        val fileName = "MatruSneh_HealthCard_${System.currentTimeMillis()}.pdf"
        val file = File(context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS), fileName)
        val document = Document(PageSize.A4)
        PdfWriter.getInstance(document, FileOutputStream(file))
        document.open()

        val orangeColor = BaseColor(230, 81, 0)
        
        // Header
        val headerFont = Font(Font.FontFamily.HELVETICA, 24f, Font.BOLD, orangeColor)
        val header = Paragraph("MATRU-SNEH HEALTH CARD", headerFont)
        header.alignment = Element.ALIGN_CENTER
        document.add(header)

        val subHeaderFont = Font(Font.FontFamily.HELVETICA, 14f, Font.NORMAL)
        val subHeader = Paragraph("ಮಾತೃ ಸ್ನೇಹ ಆರೋಗ್ಯ ಕಾರ್ಡ್", subHeaderFont)
        subHeader.alignment = Element.ALIGN_CENTER
        document.add(subHeader)

        document.add(Paragraph(" ")) // Spacing
        
        // Mother Info Table
        val infoTable = PdfPTable(2)
        infoTable.widthPercentage = 100f
        infoTable.addCell(createCell("Mother's Name:", true))
        infoTable.addCell(createCell(motherName, false))
        infoTable.addCell(createCell("Pregnancy Week:", true))
        infoTable.addCell(createCell(pregnancyWeek.toString(), false))
        infoTable.addCell(createCell("Export Date:", true))
        infoTable.addCell(createCell(SimpleDateFormat("yyyy-MM-dd", Locale.getDefault()).format(Date()), false))
        document.add(infoTable)

        document.add(Paragraph(" "))
        document.add(Paragraph("Last Vitals Records", Font(Font.FontFamily.HELVETICA, 16f, Font.BOLD)))
        document.add(Paragraph(" "))

        // Vitals Table
        val vitalsTable = PdfPTable(4)
        vitalsTable.widthPercentage = 100f
        vitalsTable.addCell(createCell("Date", true))
        vitalsTable.addCell(createCell("Weight (kg)", true))
        vitalsTable.addCell(createCell("BP (S/D)", true))
        vitalsTable.addCell(createCell("Status", true))

        vitalsData.take(10).forEach { record ->
            vitalsTable.addCell(createCell(record.date, false))
            vitalsTable.addCell(createCell(record.weightKg.toString(), false))
            vitalsTable.addCell(createCell("${record.systolic}/${record.diastolic}", false))
            vitalsTable.addCell(createCell(if (record.isBPHigh) "HIGH" else "Normal", false))
        }
        document.add(vitalsTable)

        document.add(Paragraph(" "))
        val footer = Paragraph("Generated by Matru-Sneh App — Empowering Rural Maternal Health", Font(Font.FontFamily.HELVETICA, 10f, Font.ITALIC))
        footer.alignment = Element.ALIGN_CENTER
        document.add(footer)

        document.close()
        return file
    }

    private fun createCell(text: String, isHeader: Boolean): PdfPCell {
        val font = if (isHeader) Font(Font.FontFamily.HELVETICA, 12f, Font.BOLD) else Font(Font.FontFamily.HELVETICA, 12f)
        val phrase = Phrase(text, font)
        val cell = PdfPCell(phrase)
        cell.setPadding(8f)
        if (isHeader) {
            cell.backgroundColor = BaseColor(255, 243, 224)
        }
        return cell
    }
}
